In [1]:
%reset -f 
import pickle
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import UnivariateSpline
import time
import derivatives as d
from chameleon import Chameleon

In [2]:
chameleon = Chameleon(E=10)

In [3]:
active_stress = np.linspace(1, 10, chameleon.n_elems)

In [4]:
# active_stress = (1/10)*active_stress**2

In [5]:
active_stress

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Is this is too slow? In order to do RL I want to be able to simulate much faster than this. (Jax?)

### could also simulate for a shorter time when I want to.

I could almost already build this as an RL environment. Just need to wrap this around a gym environment, reset the thing according to the most recent position and have each specification of torque account for a smaller period of simulation time. Maybe do 1000 steps of sim instead of 10000.



In [6]:
# %%time
# chameleon.step(active_stress)

In [7]:
%%time
chameleon.forward_simulate(active_stress, sim_steps=1000)

CPU times: user 204 ms, sys: 4.7 ms, total: 209 ms
Wall time: 206 ms


# Error indicates that the element on the end is not farther out than the element that is next to last. 

I had this issue before and I am not sure how to solve it right now.

In [8]:
chameleon.pos_f

array([0.        , 1.16017895, 1.70626605, 2.22434505, 2.71647635,
       3.18452367, 3.63017687, 4.0549718 , 4.46030743, 4.57141854])

In [9]:
chameleon.disp_current

array([0.        , 1.04906783, 1.48404383, 1.89101171, 2.27203191,
       2.62896811, 2.9635102 , 3.27719402, 3.57141854, 3.57141854])

In [10]:
dx = chameleon.pos_0[-1] - chameleon.pos_0[-2]

In [11]:
factor = 2*dx*active_stress[-1]/chameleon.E

In [12]:
factor

0.22222222222222232

In [13]:
chameleon.disp_current[-1]

3.571418538694312

In [14]:
chameleon.disp_previous[-1]

3.457924982777579

# some hacky code to store the position history for later visualization.


In [15]:
history = []
for i in range(len(chameleon.position_history)):
    x_p = chameleon.position_history[i]
    y = np.zeros(10)
    ar = np.vstack((x_p, y)).T
    history.append(ar)

with open("history.txt", "wb") as fp:
    pickle.dump(history, fp)

