In [1]:
%reset -f 
import matplotlib.pyplot as plt
import numpy as np
from scipy.interpolate import UnivariateSpline
import time
import derivatives as d
from forward_sim import Chameleon

In [2]:
chameleon = Chameleon(T=1, E=10)

In [3]:
active_torque = 1/10*np.linspace(1, 10, chameleon.n_elems)

In [4]:
active_torque

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
chameleon.n_steps

1000

## This is too slow. In order to do RL I want to be able to simulate much faster than this. (Jax?)

### could also simulate for a shorter time when I want to.

I could damn near already build this as an RL environment. Just need to wrap this around a gym environment, reset the thing according to the most recent position and have each specification of torque account for a smaller period of simulation time. Maybe do 1000 steps of sim instead of 10000.


In [6]:
%%time
chameleon.step(active_torque)

CPU times: user 720 µs, sys: 154 µs, total: 874 µs
Wall time: 775 µs


## Why this error when I increase young's modulus? That seems weird

In [7]:
%%time
chameleon.forward_simulate(active_torque)

ValueError: x must be increasing if s > 0

In [11]:
chameleon.pos_f

array([0.        , 2.35228848, 2.69303553, 3.02001559, 3.31734221,
       3.57127147, 3.77068376, 3.90741218, 3.97639546, 3.97565265])

In [12]:
chameleon.disp_current

array([0.06157795, 0.03833096, 0.04387748, 0.0503022 , 0.05687801,
       0.06291581, 0.06781202, 0.07108787, 0.07241634, 0.07163474])

In [39]:
len(chameleon.position_history)

1000

# I would like to see some kind of visualization of the position history here